name: Lets Start neva
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "telethn"
          replace: "client"
      - name: Pull All Updates
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'by @mr_srlock yo yoðŸ¥³'
          commit_options: '--no-verify'
          repository: .
          commit_user_name: MR-SHRLCK
          commit_user_email: 72887386+Mr-SHRLCK@users.noreply.github.com
          commit_author: MR-SHRLCK <72887386+Mr-SHRLCK@users.noreply.github.com>
